POST http://localhost:5001/job-postings
Content-Type: application/json
Cookie: access_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im51dXR0aS5ueXlzc29uZW5AZ21haWwuY29tIiwiaWQiOiJmOThjYjZlOS04ZDVmLTRiNDctYTY3NC0zNzBmMjNlNjBiZTEiLCJpYXQiOjE3NzE5MTk2MzN9.VsEHzklSEL96jSoPgKcaDdqO8Nu-2-R4UNGF4EqylcE"

{
    "title": "Software Engineer",
    "description": "Develop and maintain software applications.",
    "department": "Tech Corp",
    "location": "New York, NY",
    "salaryRange": "100000",
    "requirements": "Bachelor's degree in Computer Science or related field",
    "closingDate": "2024-12-31",
    "employmentType": "Full-time",
    "seniority": "Mid-level"
}